<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Consul" Version="1.7.14.7" />
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Winton.Extensions.Configuration.Consul" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Order.Application\Order.Adapters.csproj" />
  </ItemGroup>

</Project>
